server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/shipment_db

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

spring:
  cloud:
    stream:
      defaultBinder: rabbit

app:
  test: loaded-shipment-service
